version: '3.4'
services:
  db_dev:
    image: mysql:8.0
    container_name: my_sql_dev #set container name
    environment:
      MYSQL_ROOT_PASSWORD: "mysql" #set root pswd
      MYSQL_DATABASE: "testedb"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3310:3306' # set port host:container
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /home/bernardo/my_sql/dev:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
